### PR TITLE
Fix known installation issues and update image summary

### PR DESCRIPTION
**Pull request by zihaolucky**
@piiswrong 

Excited to launch this PR, using Travis-CI for building Python wheel. Then upload to PYPI so we could install tensorboard with `pip install tensorboard`. BTW, I make a patch for hacking the compiling time issue, but not solve all the TF ops. Some other known issues like https://github.com/dmlc/tensorboard/issues/13 and https://github.com/dmlc/tensorboard/issues/10#issuecomment-280897856 could be fixed.

Could you please review the info in `setup.py`? As it's used in our PYPI page.

### CODE REVIEW

**Comment by zihaolucky** [comment]
Here's a most recent Travis log, https://travis-ci.org/zihaolucky/tensorboard/builds/204655296

BTW, how to install the python package `cv2`? As the `image` summary needs `import cv2`

**Comment by piiswrong** [comment]
opencv is not on pip
I recommend you use pillow or skimage instead

Zihao Zheng <notifications@github.com>于2017年2月23日 周四上午8:50写道：

**Comment by zihaolucky** [comment]
@piiswrong use pillow now. I tested in my own env and it worked.

**Comment by piiswrong** [comment]
Don't build the entire distro everytime... That's too many jobs for travis.
Make a tensorboard-distro repo yourself and do distro from there. Only do testing here.

**Comment by zihaolucky** [comment]
move distro to https://github.com/zihaolucky/tensorboard-distro now. Now this PR fix some known installation issues in Linux and update image summary.

**Pull request merged**
