### PR TITLE
Feature/support tensorboard rendering part

### PR DESCRIPTION
**Pull request by zihaolucky**
@piiswrong 

In this PR, we provide `installer.sh` for bazel build TensorBoard, and `build_pip_package.sh` for `.whl` file. Once we install TensorBoard using the `.whl`, we get both logging and rendering part. To support rendering part, I found we would get `tensorboard.runfiles` and `tensorboard`(a python binary for simply using `tensorboard --logdir=xxx`) and I've packed them all into the `.whl`.

To make this project easy-to-maintain, I haven't try to strip the tensorboard's code. I want to automate this process with travis-ci and generate the `.whl` file so that user can easily install this package like TensorFlow does,  I would submit another PR for this after I figure out how to do.

### CODE REVIEW

**Comment by zihaolucky** [comment]
But I have to do some change in the generated `tensorboard`'s `FindModuleSpace` before merging. The code finds the location of `tensorboard.runfiles`, which is placed under site-packages, while the `tensorboard` binary is placed in `somewhere/bin/tensorboard` which would lead to `'Cannot find .runfiles directory`

```python
# Find the runfiles tree
def FindModuleSpace():
  # Follow symlinks, looking for my module space
  stub_filename = os.path.abspath(sys.argv[0])
  while True:
    # Found it?
    module_space = stub_filename + '.runfiles'
    if os.path.isdir(module_space):
      break

    runfiles_pattern = "(.*\.runfiles)/.*"
    if IsWindows():
      runfiles_pattern = "(.*\.runfiles)\\.*"
    matchobj = re.match(runfiles_pattern, os.path.abspath(sys.argv[0]))
    if matchobj:
      module_space = matchobj.group(1)
      break

    raise AssertionError('Cannot find .runfiles directory for %s' %
                         sys.argv[0])
  return module_space
```

How can I add the following code into this after copy the generated code from bazel-bin? 

```python
import site

# add these to FindModuleSpace
    for mod in site.getsitepackages():
      module_space = mod + '/tensorboard/tensorboard' + '.runfiles'
      if os.path.isdir(module_space):
        return module_space
```

**Comment by piiswrong** [comment]
try git apply xxx.patch?

**Comment by piiswrong** [comment]
I think this solution looks good. How fast is it to build this? We only need to build tensorboard, not the entire tensorflow right?
We can merge this into main repo as a submodule after the following steps:
1. add readme for how to install dependencies and tensorboard
2. write some jupyter notebooks to explain usage

**Comment by zihaolucky** [comment]
@piiswrong Thanks for your advice.

Yes, we would build tensorboard only, I've compared the difference between the tensorboard-only and the entire tensorflow, their bazel-bin is different. The speed depends on the network, it downloads dependencies for front/back-end and the entire build process could be finished in 10mins. 

I would add more details in README and tutorials later, thank you again.

**Comment by zihaolucky** [comment]
@piiswrong I'm still confused in the `FindModuleSpace` issue.

Here's the code structure:

```
├── LICENSE
├── Makefile
├── README.md
├── installer.sh
├── python
│   ├── README.md
│   ├── setup.py
│   └── tensorboard
│       ├── __init__.py
│       ├── crc32c.py
│       ├── event_file_writer.py
│       ├── record_writer.py
│       ├── src
│       │   └── __init__.py
│       ├── summary.py
│       └── writer.py
├── tensorboard
│   └── src
│       ├── event.proto
│       ├── resource_handle.proto
│       ├── summary.proto
│       ├── tensor.proto
│       ├── tensor_shape.proto
│       └── types.proto
└── tools
    └── pip_package
        ├── MANIFEST.in
        ├── README
        └── build_pip_package.sh
```

After we run `installer.sh`, we get `tensorboard` and `tensorboard.runfiles/`:

```
├── LICENSE
├── Makefile
├── README.md
├── installer.sh
├── python
│   ├── MANIFEST.in
│   ├── README
│   ├── README.md
│   ├── setup.py
│   └── tensorboard
│       ├── __init__.py
│       ├── crc32c.py
│       ├── event_file_writer.py
│       ├── record_writer.py
│       ├── src
│       ├── summary.py
│       ├── tensorboard           <--- python binary
│       ├── tensorboard.runfiles  <--- directory/dependencies
│       └── writer.py
├── tensorboard
│   └── src
│       ├── event.proto
│       ├── resource_handle.proto
│       ├── summary.proto
│       ├── tensor.proto
│       ├── tensor_shape.proto
│       └── types.proto
└── tools
    └── pip_package
        ├── MANIFEST.in
        ├── README
        └── build_pip_package.sh
```

I've googled and read the materials for applying a patch using git. But how can create a patch using git diff if the `tensorboard` is generated? I have to `git add tensorboard` and then make my change, then follow the steps as you mentioned while I should not commit the `tensorboard`?

**Pull request merged**
