### PR TITLE
fix stringIO issue under python2.7

### LINKED ISSUE #31: StringIO issue when using python2
In the summary.py

"from six import StringIO" is not working for python 2.7. 
So I got this error, 
File "/home/hz138/anaconda2/lib/python2.7/site-packages/tensorboard/summary.py", line 186, in make_image
    output = StringIO.StringIO()
AttributeError: class StringIO has no attribute 'StringIO'

### PR DESCRIPTION
**Pull request by zihaolucky**
fix #31

### CODE REVIEW

**Comment by hanzhanggit** [comment]
Hi,

Do you fix this in the PyPI？my labmates told me he still faces the same issue

**Comment by zihaolucky** [comment]
@hanzhanggit I haven't update the PyPI yet, will try to fix it tonight. Then I will let you know, thx.

**Comment by zihaolucky** [comment]
Hi @hanzhanggit 

please install the latest version, `1.0.0a7` and varify the issue again, thank you.

**Comment by zzw1123** [comment]
Hi, I have the same error of stringIO and when I try to update the version of tensorboard by “pip install tensorboard==1.0.0a7”, another error occurs: Could not find a version that satisfies the requirement tensorboard==1.0.0a7 (from versions: 1.0.0a3, 1.0.0a4, 1.0.0a5, 1.0.0a6, 1.6.0rc0, 1.6.0, 1.7.0, 1.8.0)

could you please tell me how to solve it? @zihaolucky

**Comment by zihaolucky** [comment]
@zzw1123 The pip package is no longer this version, you can use `pip install mxboard` to use https://github.com/awslabs/mxboard which has more features and easier to use.

**Pull request merged**
