### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by zihaolucky**
Update README.

### CODE REVIEW

**Comment by piiswrong** [comment]
Looks. good.
After you have some tutorials I'll help you verify and maybe get some more early adopters.

You are also welcome to write a blog post here: http://dmlc.ml/

**Comment by zihaolucky** [comment]
That's cool. Thank you!!

**Comment by zihaolucky** [comment]
Hi @piiswrong I'm writing a tutorial, trying to introduce the vanish gradient problem using visualization. And I want to directly use the cifar10 example in mxnet/example, is there any recommended way to do this? Or I should write it from scratch.

**Comment by piiswrong** [comment]
you can copy the code from example for now.

**Comment by zihaolucky** [comment]
@piiswrong Is there any way to get gradients if I use `module` or the old `FeedForward` API? Or I have to use `executor` to do this? I didn't find this usage in document.

**Comment by piiswrong** [comment]
get gradient for logging? You can use monitor. See example/python-howto/monitor

**Pull request merged**
